os: linux
dist: xenial
language: shell
arch: amd64

jobs:
  include:
    - stage: A
      script: true
    - stage: B
      script:
        - echo DONE
    - stage: C
      script:
        - echo "DONE"
