os: linux
language: go
go: master

addons:
  apt:
    packages:
    - gcc
  update: true
  upgrade: true

install: skip

script:
  - uname -a
jobs:
  include:
    - dist: trusty
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy
