os: linux
dist: focal
language: node_js
node_js:
  - 16
  - 14
  - 12
  - 10
  - 9
  - 8
before_install:
  #- git config --global url."ssh://git@".insteadOf git://
  - npm install -g npm@8.10.0
  #- sudo pip install --upgrade pip

install:
  - npm install

jobs:
  include:
    - script:
        - sleep 1
    - script:
        - sleep 2
    - script:
        - sleep 3
    - script:
        - sleep 4
    - script:
        - sleep 5
    - script:
        - sleep 6
    - script:
        - sleep 7
    - script:
        - sleep 8
    - script:
        - sleep 9
    - script:
        - sleep 10
    - script:
        - sleep 11
    - script:
        - sleep 12
    - script:
        - sleep 13
    - script:
        - sleep 14
    - script:
        - sleep 15
    - script:
        - sleep 16
    - script:
        - sleep 17
    - script:
        - sleep 18
    - script:
        - sleep 19
    - script:
        - sleep 20
    - script:
        - sleep 21
    - script:
        - sleep 22
    - script:
        - sleep 23
    - script:
        - sleep 24
    - script:
        - sleep 25
    - script:
        - sleep 26
    - script:
        - sleep 27
    - script:
        - sleep 28
    - script:
        - sleep 29
    - script:
        - sleep 30
    - script:
        - sleep 31
    - script:
        - sleep 32
    - script:
        - sleep 33
    - script:
        - sleep 34
    - script:
        - sleep 35
    - script:
        - sleep 36
    - script:
        - sleep 37
    - script:
        - sleep 38
    - script:
        - sleep 39
    - script:
        - sleep 40
    - script:
        - sleep 41
    - script:
        - sleep 42
    - script:
        - sleep 43
    - script:
        - sleep 44
    - script:
        - sleep 45
    - script:
        - sleep 46
    - script:
        - sleep 47
    - script:
        - sleep 48
    - script:
        - sleep 49
    - script:
        - sleep 50
    - script:
        - sleep 51
    - script:
        - sleep 52
    - script:
        - sleep 53
    - script:
        - sleep 54
    - script:
        - sleep 55
    - script:
        - sleep 56
    - script:
        - sleep 57
    - script:
        - sleep 58
    - script:
        - sleep 59
    - script:
        - sleep 60
    - script:
        - sleep 61
    - script:
        - sleep 62
    - script:
        - sleep 63
    - script:
        - sleep 64
    - script:
        - sleep 65
    - script:
        - sleep 66
    - script:
        - sleep 67
    - script:
        - sleep 68
    - script:
        - sleep 69
    - script:
        - sleep 70
    - script:
        - sleep 71
    - script:
        - sleep 72
    - script:
        - sleep 73
    - script:
        - sleep 74
    - script:
        - sleep 75
    - script:
        - sleep 76
    - script:
        - sleep 77
    - script:
        - sleep 78
    - script:
        - sleep 79
    - script:
        - sleep 80
    - script:
        - sleep 81
    - script:
        - sleep 82
    - script:
        - sleep 83
    - script:
        - sleep 84
    - script:
        - sleep 85
    - script:
        - sleep 86
    - script:
        - sleep 87
    - script:
        - sleep 88
    - script:
        - sleep 89
    - script:
        - sleep 90
