jobs:
  include:
    - os: linux
      dist: xenial
      language: java
      before_install:
      - sudo apt-get -y remove default-jdk
      - sudo add-apt-repository -y ppa:openjdk-r/ppa
      - sudo apt -y update
      - sudo apt install -y openjdk-13-jdk
      - sudo  update-java-alternatives --list
      #- sudo  update-java-alternatives --set openjdk-13-jdk
      - java -version
      script: true
