jobs:
  include:
    - os: linux
      dist: focal
      language: shell
      vm:
        size: medium
      script: true
      
    - os: linux
      dist: focal
      language: shell
      vm:
        size: large
      script: true
      
    - os: linux
      dist: focal
      language: shell
      vm:
        size: x-large
      script: true
