jobs:
 include:
  - arch: amd64
    os: linux
    dist: focal
    language: ruby
    ruby: 3.0
    script:
     - ruby -v
  - os: osx
    osx_image: xcode13.1
    language: ruby
    before_install:
     #- gem update --system
     - rvm install 3.0.3
     - rvm ruby-3.0.3 do rvm gemset create
     - rvm use 3.0.3
    script:
     - ruby -v
