jobs:
  include:
    - os: linux
      dist: trusty
      language: java
      jdk: openjdk9
      script: true
    - os: linux
      dist: xenial
      language: java
      jdk: openjdk9
      script: true
    - os: linux
      dist: bionic
      language: java
      jdk: openjdk9
      script: true
    - os: linux
      dist: focal
      language: java
      jdk: openjdk9
      script: true
