os: linux
dist: bionic
language: ruby
addons:
  apt:
    packages:
      - postgresql-14
      - postgresql-client-14
env:
  global:
    - PGPORT=5433
    - PGUSER=postgres
before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo systemctl reload postgresql
  - sleep 5
  - psql --version
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate
script:
  - bundle exec rspec --format documentation
before_deploy:
  - openssl version
  - curl -o openssl-1.1.1g.tar.gz https://www.openssl.org/source/openssl-1.1.1g.tar.gz
  - tar -zxf openssl-1.1.1g.tar.gz && cd openssl-1.1.1g && ./config
  - sudo make install
  - sudo ln -sf /usr/local/bin/openssl /usr/bin/openssl
  - sudo ldconfig
  - openssl version
deploy:
  provider: heroku
  api_key: $API_KEY
  app: tci-test-runs
  run: "rake db:migrate"
  On:
    branch: rails-app
  edge: true
