os: linux
dist: focal
rvm: 2.6.7

addons:
  apt:
    packages:
      - ca-certificates

services:
  - redis
  - mongodb
before_install:
  - mongo --version
  - apt update -y
  - apt upgrade -y
script:
  - mongo --version
