jobs:
  include:
    - os: linux
      dist: trusty
      language: android
      jdk: openjdk11
      before_install:
      - java -version
      script: true
    - os: linux
      dist: xenial
      language: java
      jdk: openjdk13
      before_install:
      - java -version
      script: true
    - os: linux
      dist: focal
      language: java
      jdk: openjdk13
      before_install:
      - java -version
      script: true
