language: generic
os: linux
dist: xenial
before_install:
  - cd $HOME && curl -LO https://saucelabs.com/downloads/sc-4.8.0-linux.tar.gz
  - tar xvf $HOME/sc-4.8.0-linux.tar.gz
  - export PATH="$HOME/sc-4.8.0-linux/bin:$PATH"
  - cd $TRAVIS_BUILD_DIR
script:
  - sc
