os: linux
language: shell
dist: xenial
group: dev
before_script:
  - pyenv global 3.7.2
jobs:
  include:
    - script:
        - python --version
        #- docker version  # Verify docker downgrade.
        #- docker-compose --version
