language: shell
jobs:
  include:
    - os: linux
      dist: focal
      jdk: openjdk17
    - os: linux
      dist: focal
      jdk: openjdk13
    - os: linux
      dist: focal
      jdk: openjdk11
script: true
