os: linux
dist: focal
rvm: 2.6.7

addons:
  apt:
    packages:
      - ca-certificates

services:
  - redis
  - mongodb
before_install:
  - mongo --version
  - sudo apt-get update -y
  - sudo apt-get install -y mongodb-org
script:
  - mongo --version
