os: linux
dist: xenial
language: node_js

jobs:
  include:
    - stage: "TESTS"
      node_js: '12'
      script: true
    - stage: "TESTS"
      node_js: '13'
      script: true
    - stage: "TESTS"
      node_js: '14'
      script: true
    - stage: "TESTS"
      node_js: '15'
      script: true
