os: linux
node_js: '13'
language: node_js
dist: xenial
services:
  - docker
before_install:
- sudo apt remove docker*
- curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
- sudo apt-get update
- sudo apt-get install docker-ce=18.03.1~ce-0~ubuntu -yq
- sudo chmod 666 /var/run/docker.sock
script:
  - python --version
  - docker version
