jobs:
 include:
  - arch: amd64
    os: linux
    dist: trusty
    language: php
    php: 7.2
    script:
     - sudo apt-get update && sudo apt-get install google-cloud-sdk=350.0.0-0
     - gcloud version
