jobs:
  include:
    - os: linux
      dist: xenial
      language: java
      jdk: openjdk9
      before_install:
      - java -version
      script: true
    - os: linux
      dist: trusty
      language: android
      before_install:
      - sudo add-apt-repository -y ppa:openjdk-r/ppa
      - sudo apt-get -y update
      - sudo apt install -y openjdk-11-jdk
      - java -version
      script: true
    - os: linux
      dist: xenial
      language: java
      jdk: openjdk13
      before_install:
      - java -version
      script: true
