jobs:
  include:
  - os: linux
    dist: focal
    language: go
    go:
      - 1.12.1
    git:
      submodules: false
    script:
      - echo done
before_install:
  - openssl aes-256-cbc -K $encrypted_f26e077a6941_key -iv $encrypted_f26e077a6941_iv
    -in .travis/test_key.enc -out /tmp/test_key -d
  - chmod 600 /tmp/test_key
  - eval "$(ssh-agent -s)"
  - ssh-add /tmp/test_key
