jobs:
  include:
    - stage: "TESTS"
      os: linux
      node_js: '13'
      language: node_js
      dist: xenial
      script: true
    - 
      script: true
    - 
      script: true
    - 
      script: true
