jobs:
  include:
    - os: linux
      dist: focal
      jdk: openjdk17
      script:
        - sleep 1
    - os: linux
      dist: focal
      jdk: openjdk13
      script:
        - sleep 2
    - os: linux
      dist: focal
      jdk: openjdk11
      script:
        - sleep 3
