jobs:
  include:
    - os: linux
      dist: focal
      language: ruby
      ruby:
        - 2.6.6
      services:
        - postgresql
      before_script:
        - psql -c max_locks_per_transaction=1024
        - sudo systemctl restart postgresql.service
      script: true
