jobs:
  include:
  - stage: One
    os: linux
    dist: focal
    language: shell
    script: true
before_install:
- openssl aes-256-cbc -K $encrypted_90e72a4bf65a_key -iv $encrypted_90e72a4bf65a_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d