dist: focal
language: ruby
rvm: 2.7.4
services:
- postgresql
addons:
  apt:
    packages:
      - postgresql-13
      - postgresql-client-13
    update: true
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script: true
