jobs:
  include:
    - os: linux
      dist: xenial
      language: java
      jdk: openjdk9
      before_install:
      - java -version
      script: true
    - os: linux
      dist: trusty
      language: android
      before_install:
      - sudo apt install -y openjdk-11-jdk
      - java -version
      script: true
    - os: linux
      dist: xenial
      language: java
      before_install:
      - sudo apt install -y openjdk-13-jdk
      - java -version
      script: true
