jobs:
  include:
    - os: linux
      dist: xenial
      arch: arm64
      language: shell
      script: true
    - os: linux
      dist: bionic
      arch: arm64
      language: shell
      script: true
    - os: linux
      dist: focal
      arch: arm64
      language: shell
      script: true
