language: node_js
node_js:
  - 14
cache:
  npm: false

before_install:
  - npm install -g npm@6.14.7
  - sudo pip install --upgrade pip

install:
  - npm install -g travis-ci-cloudfront-invalidation
  - npm install

script:
  - sleep 1
