os: linux
dist: focal
language: shell
jobs:
  include:
    - if: tag IS present
      script:
        - echo "Build on Travis tag"
    - if: type IS pull_request
      script:
        - echo "Pull request builds"