arch: arm64-graviton2
virt: vm
os: linux
dist: focal
group: edge
language: minimal
before_install:
- echo "checking disk space before install"
- sudo df -h
- sudo du -h /var/lib/docker
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce docker-ce-cli
- sudo df -h
- echo "cleaning apt"
- sudo apt-get clean
- sudo df -h
- sudo service docker start
- echo "pruning docker"
- docker system prune -a -f
- sudo df -h
script:
  - sleep 3
