language: node_js
node_js:
  - 14
cache:
  npm: false

before_install:
  #- git config --global url."ssh://git@".insteadOf git://
  - npm install -g npm@7.24.2
  - sudo pip install --upgrade pip

install:
  - npm install -g travis-ci-cloudfront-invalidation
  - npm install

script:
  - sleep 1
