services:
  - postgresql
jobs:
  include:
    - os: linux
      dist: focal
      language: ruby
      script:
        - psql -c 'create database travis_ci_test;' -U postgres
        - sleep 5
        - psql -c 'create database travis_ci_test;' -U travis
