os: linux
dist: focal
install: skip
before_script:
  - mysql --version
  - mysql -uroot -e "SHOW VARIABLES LIKE 'innodb_page_size';"
  - mysqld --innodb-page-size=32768
  - sudo systemctl restart mysql
script:
  - mysql -uroot -e "SHOW VARIABLES LIKE 'innodb_page_size';"
