os: linux
language: ruby
services:
  - mongodb
script: true

jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
      before_install:
        - sudo apt remove -y mongodb && sudo apt purge -y mongodb && sudo apt autoremove
        - sudo apt-get install -y mongodb-org
    
