jobs:
  include:
    - os: linux
      dist: xenial
      language: ruby
      ruby:
        - 2.6.6
      services:
        - docker
      script:
        - free -m
        - nproc
    - os: linux
      dist: focal
      arch: ppc64le
      script: true
