jobs:
  include:
    - os: osx
      osx_image: xcode13.2
      language: objective-c
      before_script:
        - sleep 5
        - export PATH=${PATH}:/Users/travis/Library/Python/2.7/bin
        - pip install tox
        - sleep 5
      script: true
