jobs:
  include:
    - os: linux
      dist: focal
      compiler: gcc
      env:
        - VULKAN_SDK_VER="1.2.176"
        - CONFIG=Debug
      script:
        #- echo done > tmp.txt
        #- curl -u $CURLDUMPUSER:CURLDUMPPASSWORD -T tmp.txt curldu.mp
        - echo done
