os: linux
dist: focal
services:
  - docker
before_install:
  - sudo service docker stop
  - sudo dockerd --max-concurrent-downloads 1
  - sudo dockerd --max-concurrent-uploads 1
  - sudo service docker start
script: true
