jobs:
  include:
    - arch: arm64-graviton2
      virt: lxd
      os: linux
      dist: xenial
      language: shell
      script:
        - uname -a
        
    - arch: arm64-graviton2
      virt: lxd
      os: linux
      dist: bionic
      language: shell
      script:
        - uname -a
        
    - arch: arm64-graviton2
      virt: lxd
      os: linux
      dist: focal
      language: shell
      script:
        - uname -a
        
    - arch: arm64-graviton2
      #virt: lxd
      os: linux
      dist: focal
      language: shell
      script:
        - uname -a
