jobs:
  include:
    - os: linux
      dist: xenial
      before_script:
        - eval "$(pyenv init --path)"
        - pyenv install 3.7.10
        - pyenv global 3.7.10
      script:
        - python -V
