os: linux
dist: bionic
language: ruby
ruby:
  - 2.7.4
  - 2.6.10
  - 3.1.1
addons:
  apt:
    packages:
      - postgresql-14
      - postgresql-client-14
env:
  global:
    - PGPORT=5433
    - PGUSER=postgres
before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo systemctl reload postgresql
  - sleep 5
  - psql --version
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate
script:
  - bundle exec rspec --format documentation
deploy:
  provider: heroku
  api_key: $API_KEY
  app: tci-test-runs
  run: "rake db:migrate"
  On:
    branch: rails-app
  edge: true
