jobs:
  include:
    - os: osx
      osx_image: xcode12.2
      language: objective-c
      before_install:
        - xcodebuild -version
      install:
        - make V=1
      script:
        - uname -p
        - uname -a
