jobs:
  include:
    - os: linux
      dist: xenial
      language: php
      php:
        - 8.0snapshot
      script: true
      
    - os: linux
      dist: bionic
      language: php
      php:
        - 8.0snapshot
      script: true
