os: linux
language: shell

install: skip

script:
  - sleep 1
jobs:
  include:
    - stage: test-1
      name: trusty
      dist: trusty
    - stage: test-2
      name: xenial
      dist: xenial
    - stage: test-3
      name: bionic
      dist: bionic
    - stage: test-4
      name: focal
      dist: focal
    - stage: test-5
      name: jammy
      dist: jammy
