os: linux
dist: bionic
language: ruby
addons:
  apt:
    packages:
      - postgresql-14
      - postgresql-client-14
env:
  global:
    - PGPORT=5433
    - PGUSER=postgres
before_script:
  - bundle exec rake db:create db:migrate
script:
  - bundle exec rspec --format documentation
  - psql --version
