os: linux
dist: focal
language: shell
services:
  - docker
before_install:
  - sudo systemctl restart docker
  - cat /etc/docker/daemon.json
  - sudo touch /etc/docker/daemon.json
  - echo '{"max-concurrent-downloads":1}' | sudo tee /etc/docker/daemon.json
  - sudo systemctl restart docker
  - cat /etc/docker/daemon.json
script: true
