jobs:
  include:
    - os: linux
      dist: xenial
      language: php
      php: 5.6.0
      script: true
      
    - os: linux
      dist: xenial
      language: php
      php: 7.0.0
      script: true
      
    - os: linux
      dist: xenial
      language: php
      php: 7.1.0
      script: true
      
    - os: linux
      dist: xenial
      language: php
      php: 7.2.0
      script: true
      
    - os: linux
      dist: xenial
      language: php
      php: 7.3.0
      script: true
      
    - os: linux
      dist: xenial
      language: php
      php: nightly
      script: true
