language: android
dist: trusty
jdk: openjdk11
android:
   components:
      - tools
      - platform-tools
      - tools
      - extra-google-google_play_services
      - extra-android-m2repository
   licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

before_install:
   - touch $HOME/.android/repositories.cfg
   # Android API Level 31
   - yes | sdkmanager "platforms;android-31"
   - yes | sdkmanager "build-tools;31.0.0"
   - yes | sdkmanager "build-tools;31.0.0"
   - ls $ANDROID_HOME/build-tools/31.0.0
   - ls $ANDROID_HOME/build-tools/31.0.0/lib
   - mv $ANDROID_HOME/build-tools/31.0.0/d8 $ANDROID_HOME/build-tools/31.0.0/dx 
   - mv $ANDROID_HOME/build-tools/31.0.0/lib/d8.jar $ANDROID_HOME/build-tools/31.0.0/lib/dx.jar
   - ls $ANDROID_HOME/build-tools/31.0.0
   - ls $ANDROID_HOME/build-tools/31.0.0/lib
   - sdkmanager --update
   - sdkmanager --list
script: true
