jobs:
  include:
    - os: linux
      dist: focal
      env:
        global:
          - PGPORT=5433
          - PGUSER=travis
      language: ruby
      ruby:
        - 2.6.6
      services:
        - postgresql
      addons:
        postgresql: 12
        apt:
          update: true
          packages:
            - postgresql-12
            - postgresql-client-12
      before_script:
        - postgres -c max_locks_per_transaction=1024 --config-file /etc/postgresql/12/main/postgresql.conf
        - sudo systemctl restart postgresql.service
      script: true
