language: node_js
sudo: required
services:
- docker
node_js:
- '14'
arch:
- arm64-graviton2
os: linux
virt: vm
group: edge
addons:
  snaps:
  - yq
script:
- echo "ENCRYPTED"
env:
  global:
    secure: DLykjBqF27tbx7iojEmyXxdCJ0mfBZPYkEoTVW/B9qPi5wVCy7nhB/EBKHHtpCA7vel0F5FNzmQ9Yor0S88uBrQPmZKe8fXIPiqYo9eYEIgSl2rOFBRcpDfsNCRAJUlyT5nHMnjfZa3Va6j6+Z0fzDte6R/l2IcuYpV1uAyhRSSP6eMBAHCvEVFqCmzX6ORoEDQgbdW/WCSZ5t7gTpRN/0ttSGv51Q2tl7ruKmp/lcjWO/gV9nl2ZoY+O9b1oNrGwUAKz/8Fs2y3zYj5e7U4c9JtPEtwUUXd+hHJz5XJpss+9XXKhOIqKgz+x0aQvclz27KiKMgDck5Sny6OWhGDwm9GvgClq4WSVKP1Hed5hShqPHZZpor8cYaoB98qtAazFEla3sFL0oYDKztRZXL50PymGojiWDVGi1g/GE5B4Ih54DJpoTSEOXoCRnQi/JVca+FjP0wsLYkoB5uu/zC7oTpCP0kusJK8QT2GY6GxqBniy/axMG9j1KOg8OPyfx209msLdWRc9/g5/H9G2Xi8eQolS+yNbu0ZGWtaikLFTMvLCSaVSeAu8LKRGTcGy4K8WM8YQ12Rq0CqRIzNHboAvoJrGxvcjE/D/swvXEXkHy8lc5V6WK1WXhTUcQHtn9mC6uY2O1rcbetv6o3j9ewnrBluPRlMI2M5nC6Z0J89EJU=
