os: linux
dist: focal
language: shell
services:
  - docker
before_install:
  - sudo systemctl restart docker
  - cat /etc/docker/daemon.json
  - docker pull python --max-concurrent-downloads=1
script: true
