jobs:
  include:
    - os: windows
      language: node_js
      node_js:
        - 13
      install:
        - nvs add lts
        - nvs link lts
        - nvs use lts
      script:
        - node -v
