jobs:
  fast_finish: true
  include:
    - env: SCRIPT_NAME=style.php
      name: "PHP Style"
    - env: SCRIPT_NAME=phan.php
      name: "PHP Phan"
    - env: SCRIPT_NAME=psalm.php
      name: "PHP Psalm"
    - env: SCRIPT_NAME=integrationTestsImage.php
      name: "PHP Integration Tests - Image"
      vm:
        size: 2x-large
    - env: SCRIPT_NAME=integrationTestsEmail.php
      name: "PHP Integration Tests - Email"
      vm:
        size: 2x-large
    - env: SCRIPT_NAME=integrationTestsPDFsAtoE.php
      name: "PHP Integration Tests - A to E"
      vm:
        size: 2x-large
    - env: SCRIPT_NAME=integrationTestsPDFsFtoR.php
      name: "PHP Integration Tests - F to R"
      vm:
        size: 2x-large
    - env: SCRIPT_NAME=integrationTestsPDFsStoZ.php
      name: "PHP Integration Tests - S to Z"
      vm:
        size: 2x-large
language: php
php:
- 7.4.22
script:
  - free -m
  - nproc
notifications:
  email:
    on_success: never
sudo: false
dist: focal
