jobs:
  include:
    - os: linux
      dist: xenial
      language: shell
      script:
        - pyenv global 3.6.7
        - python -V
    - os: linux
      dist: xenial
      language: java
      before_script:
        - eval "$(pyenv init --path)"
        - pyenv global 3.6.7
      script:
        - python -V
