os: linux
dist: xenial
language: python
cache:
  directories:
  - node_modules
python:
- '3.8'
addons:
  postgresql: '12'
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
env:
  global:
  - PGVER=12
  - PGPORT=5433
script:
  - nvm use 12
  - node -v
