os: linux
node_js: '13'
language: node_js
dist: xenial
services:
  - docker
before_install:
- sudo apt remove docker*
- curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
- sudo apt-get update
- sudo apt-get install docker-ce=18.06.0~ce~3-0~ubuntu containerd.io
- sudo chmod 666 /var/run/docker.sock # Dcoker daemon permission setting

jobs:
  include:
    - script:
        - python --version
        - docker version  # Verify docker downgrade.
        - echo $FOO
        - echo "This should run"
      if: env(FOO)=BAR
      
    - script:
        - python --version
        - docker version  # Verify docker downgrade.
        - echo $FOO
        - echo "This should not run"
      if: env(FOO)=SAMENAMEVAR
