dist: bionic
language: node_js
node_js:
  - 14
env:
  - CONFIG=Debug Platform=macos
  - CONFIG=Release PLATFORM=macos
  - CONFIG=Debug PLATFORM=iOS
  - CONFIG=Release PLATFORM=iOS
script:
  - echo $CONFIG
  - echo $Platform
