jobs:
 include:
  - arch: amd64
    os: linux
    dist: focal
    language: ruby
    ruby: 3.0
    script:
     - ruby -v
  - os: osx
    osx_image: xcode10.2
    language: ruby
    ruby: 3.0.0
    script:
     - ruby -v
