env:
  global:
    - test-var='test'

jobs:
  include:
    - import: qasimabdullah404/travis-build-config-import-file:before_install.yml@main
      if: env(test-var) is blank
      script: true
      
    -- import: qasimabdullah404/travis-build-config-import-file:before_install.yml@main
      if: env(test-var) is present
      script: true
