jobs:
  include:
    - os: linux
      dist: xenial
      language: php
      php: 5.6.0
      before_install:
        - sudo apt update && sudo apt install libgnutls-openssl27 libgnutls30
      script: true
      
    - os: linux
      dist: xenial
      language: php
      php: 7.0.0
      before_install:
        - sudo apt update && sudo apt install libgnutls-openssl27 libgnutls30
      script: true
      
    - os: linux
      dist: xenial
      language: php
      php: 7.1.0
      before_install:
        - sudo apt update && sudo apt install libgnutls-openssl27 libgnutls30
      script: true
      
    - os: linux
      dist: xenial
      language: php
      php: 7.2.0
      before_install:
        - sudo apt update && sudo apt install libgnutls-openssl27 libgnutls30
      script: true
      
    - os: linux
      dist: xenial
      language: php
      php: 7.3.0
      before_install:
        - sudo apt update && sudo apt install libgnutls-openssl27 libgnutls30
      script: true
      
    - os: linux
      dist: xenial
      language: php
      php: nightly
      before_install:
        - sudo apt update && sudo apt install libgnutls-openssl27 libgnutls30
      script: true
