os: linux
dist: focal
language: shell

jobs:
  include:
    - if: tag IS present
      script:
        - echo "Tagged build"
        - echo $TRAVIS_TAG
    - if: branch=main AND tag IS blank
      script:
        - echo "Branch build"