sudo: required
dist: trusty
language: node_js
services: docker
node_js: '14'
#group: dev
before_install:
  - sudo apt update && sudo apt install libgnutls-openssl27 libgnutls30
  - pyenv local 3.6
  - pip install -U pip
  - pip install awscli
  - wget -O - https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  - helm plugin install https://github.com/datreeio/helm-datree
script: true
