os: linux
dist: focal
language: shell

jobs:
  include:
    - if: branch=$TRAVIS_TAG AND tag IS present
      script:
        - echo "Tagged build"
    - if: branch=main AND tag IS blank
      script:
        - echo "Untagged build"