jobs:
  include:
  - os: osx
    osx_image: xcode12.1
    language: shell
    script: true
  - os: osx
    osx_image: xcode12.2
    language: shell
    script: true
  - os: osx
    osx_image: xcode12.3
    language: shell
    script: true
  - os: osx
    osx_image: xcode12.4
    language: shell
    script: true
  - os: osx
    osx_image: xcode12.5
    language: shell
    script: true
  - os: osx
    osx_image: xcode13.1
    language: shell
    script: true
