jobs:
 include:
  - arch: ppc64le
    os: linux
    dist: bionic
    script: true
  - arch: arm64
    os: linux
    dist: focal
    script: true
  - arch: s390x
    os: linux
    dist: focal
    script: true
