jobs:
  include:
    - os: osx
      osx_image: xcode13.1
      language: objective-c
      before_install:
        - brew tap homebrew/cask
        - brew install android-sdk --cask
        - export ANDROID_HOME=/usr/local/share/android-sdk
      script: true
