language: go
dist: xenial
os: linux
env:
- GIMME_DEBUG=true GIMME_TYPE=source
- GIMME_DEBUG=true GIMME_TYPE=git
- GIMME_DEBUG=true GIMME_TYPE=auto
- GIMME_DEBUG=true GIMME_TYPE=binary
go:
- master
install: skip
script: true
