jobs:
  include:
  - stage: setup
    script:
    - echo "--"
    if: env(tier) = stack
    - |
        if [ $CURRENT_STATUS == 0 ];then
            echo "----"
        fi
os: linux
dist: xenial
env:
  - tier=stack current=0
language: shell
