language: php

dist: focal

vm:
  size: 2x-large

before_script:
- pyenv install 3.9.7
- pyenv local 3.9.7
- pip install pip --upgrade --user
- pip install awscli --upgrade --user
- export PATH=$PATH:$HOME/.local/bin
- pip install --user aws-sam-cli


script:
  - free -m
  - nproc

notifications:
email:
on_failure: always
