jobs:
  include:
    - os: linux
      dist: trusty
      language: node_js
      node_js: 14
      #group: dev
      script:
        - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | /bin/bash
