language: c

compiler:
  - gcc

jobs:
  include:
    - os: windows
      name: Windows
      env:
      - BADGE=Windows
      - MAKE=mingw32-make
before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
        choco install octave.portable;
        tree /c/ProgramData/chocolatey/;
        octave --version;
    fi

script: true
