jobs:
  include:
    - os: linux
      arch: ppc64le
      dist: focal
      language: java
      jdk: openjdk8
      
      addons:
        apt:
          packages:
            - xmlstarlet
            - ruby
            - groovy
      before_script:
        - export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-8-hotspot-ppc64el
        - export PATH=$JAVA_HOME/bin:$PATH

      script:
        - groovy --version
