os: linux
dist: focal
install: skip
before_script:
  - mysql --version
  - sudo systemctl start mysql
  - mysql -uroot -e "SHOW VARIABLES LIKE 'innodb_page_size';"
  - sudo systemctl stop mysql
  - echo -e "[mysqld]\ninnodb-page-size = 32768" >> $HOME/.my.cnf
  - sudo systemctl start mysql
script:
  - mysql -uroot -e "SHOW VARIABLES LIKE 'innodb_page_size';"
