dist: focal
os: linux
language: minimal

jobs:
  allow_failures:
    env:
      - ALLOW_FAIL=true
  include:
    - stage: Workspace init.
      script: true
      workspaces:
        create:
          name: qa_test
          paths:
            - examine.txt
    - stage: Run tests
      env:
        - ALLOW_FAIL=true
      script:
        - echo Done
        - echo $TRAVIS_TEST_RESULT > examine.txt
        - cat examine.txt
      workspaces:
        use: qa_test
    - workspaces:
        use: qa_test
      env:
        - ALLOW_FAIL=true
      script:
        - cat examine.txt
        - false
        - echo $TRAVIS_TEST_RESULT
        - echo $TRAVIS_TEST_RESULT >> examine.txt
        - cat examine.txt
    - workspaces:
        use: qa_test
      script:
        - cat examine.txt
    - script:
        - echo done
    - stage: Run Failure Script
      workspaces:
        use: qa_test
      script:
        - cat examine.txt
        - status=$( cat examine.txt )
        - echo $status
        - if [[ "$status" =~ [1] ]]; then
            echo "RUN FAILURE SCRIPT";
          fi
