os: linux
dist: xenial
language: java
addons:
  apt:
    update: true
    packages:
      - bzip2
#services:
#   - docker
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - source ./install-jdk.sh --feature 9
  - echo JAVA_HOME = ${JAVA_HOME}
  - echo PATH = ${PATH}
  - ls ${JAVA_HOME}
  - java -version
script: true
