sudo: required
dist: xenial
language: node_js
services: docker
node_js: '14'
#group: dev
before_install:
  - pyenv local 3.7.2
  - pip install -U pip
  - pip install awscli
  - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | /bin/bash
  - helm plugin install https://github.com/datreeio/helm-datree
script: true
