dist: focal
os: linux

jobs:
  allow_failures:
    - script:
        - echo Done
  include:
    - stage: Run tests
      script:
        - echo Done
    - script:
        - true
    - script:
        - echo done
    - stage: Run Failure Script
      script:
        - true   
