jobs:
  include:      
    - os: linux
      dist: xenial
      language: node_js
      node_js: 'lts/*'
      before_script:
        - eval "$(pyenv init --path)"
        - pyenv install 3.9.6
        - pyenv global 3.9.6
      script:
        - python -V
