jobs:
  include:
  # Focal
    - os: linux
      arch: ppc64le
      dist: focal
      language: java
      jdk: openjdk8
      
      addons:
        apt:
          packages:
            - xmlstarlet
            - ruby
            - groovy
      before_script:
        - export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-8-hotspot-ppc64el
        - export PATH=$JAVA_HOME/bin:$PATH

      script:
        - groovy --version
        
    - include:
      os: linux
      arch: ppc64le
      dist: focal
      language: java
      jdk: openjdk11
      
      addons:
        apt:
          packages:
            - xmlstarlet
            - ruby
            - groovy
      before_script:
        - export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-11-hotspot-ppc64el
        - export PATH=$JAVA_HOME/bin:$PATH

      script:
        - groovy --version

    - os: linux
      arch: ppc64le
      dist: focal
      language: java
      jdk: openjdk14
      
      addons:
        apt:
          packages:
            - xmlstarlet
            - ruby
            - groovy
      before_script:
        - export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-14-hotspot-ppc64el
        - export PATH=$JAVA_HOME/bin:$PATH

      script:
        - groovy --version
        
    - include:
      os: linux
      arch: ppc64le
      dist: focal
      language: java
      jdk: openjdk15
      
      addons:
        apt:
          packages:
            - xmlstarlet
            - ruby
            - groovy
      before_script:
        - export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-15-hotspot-ppc64el
        - export PATH=$JAVA_HOME/bin:$PATH

      script:
        - groovy --version

    - os: linux
      arch: ppc64le
      dist: focal
      language: java
      jdk: openjdk16
      
      addons:
        apt:
          packages:
            - xmlstarlet
            - ruby
            - groovy
      before_script:
        - export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-16-hotspot-ppc64el
        - export PATH=$JAVA_HOME/bin:$PATH

      script:
        - groovy --version
        
    # Bionic
    - os: linux
      arch: ppc64le
      dist: bionic
      language: java
      jdk: openjdk8
      
      addons:
        apt:
          packages:
            - xmlstarlet
            - ruby
            - groovy
      before_script:
        - export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-8-hotspot-ppc64el
        - export PATH=$JAVA_HOME/bin:$PATH

      script:
        - groovy --version
        
    - include:
      os: linux
      arch: ppc64le
      dist: bionic
      language: java
      jdk: openjdk11
      
      addons:
        apt:
          packages:
            - xmlstarlet
            - ruby
            - groovy
      before_script:
        - export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-11-hotspot-ppc64el
        - export PATH=$JAVA_HOME/bin:$PATH

      script:
        - groovy --version
        
    - os: linux
      arch: ppc64le
      dist: bionic
      language: java
      jdk: openjdk12
      
      addons:
        apt:
          packages:
            - xmlstarlet
            - ruby
            - groovy
      before_script:
        - export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-12-hotspot-ppc64el
        - export PATH=$JAVA_HOME/bin:$PATH

      script:
        - groovy --version
        
   - os: linux
      arch: ppc64le
      dist: bionic
      language: java
      jdk: openjdk13
      
      addons:
        apt:
          packages:
            - xmlstarlet
            - ruby
            - groovy
      before_script:
        - export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-13-hotspot-ppc64el
        - export PATH=$JAVA_HOME/bin:$PATH

      script:
        - groovy --version     
    - os: linux
      arch: ppc64le
      dist: bionic
      language: java
      jdk: openjdk14
      
      addons:
        apt:
          packages:
            - xmlstarlet
            - ruby
            - groovy
      before_script:
        - export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-14-hotspot-ppc64el
        - export PATH=$JAVA_HOME/bin:$PATH

      script:
        - groovy --version
        
    - include:
      os: linux
      arch: ppc64le
      dist: focal
      language: java
      jdk: openjdk15
      
      addons:
        apt:
          packages:
            - xmlstarlet
            - ruby
            - groovy
      before_script:
        - export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-15-hotspot-ppc64el
        - export PATH=$JAVA_HOME/bin:$PATH

      script:
        - groovy --version

    - os: linux
      arch: ppc64le
      dist: focal
      language: java
      jdk: openjdk16
      
      addons:
        apt:
          packages:
            - xmlstarlet
            - ruby
            - groovy
      before_script:
        - export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-16-hotspot-ppc64el
        - export PATH=$JAVA_HOME/bin:$PATH

      script:
        - groovy --version
