jobs:
  include:
    - os: linux
      dist: xenial
      script:
        - echo FOO
    - os: linux
      dist: bionic
      script:
        - echo BAR
    - os: linux
      dist: focal
      script:
        - echo FOO
