dist: xenial
language: ruby
rvm:
  - 2.5.7
before_install:
  - gem install bundler -v '1.17.3'
before_script:
- sleep 2
- sudo chown -R $USER:elasticsearch /etc/default/elasticsearch
- sudo service elasticsearch restart
- curl -XGET 'http://localhost:9200'
- elasticsearch --version
services:
  - postgresql
  - mysql
  - elasticsearch
  - redis-server
script:
  - sleep 5
addons:
  postgresql: "9.4"
  apt:
    sources:
      - elasticsearch-2.x
    packages:
      elasticsearch
