env:
  global:
    - test-var='test'
import:
  - source: qasimabdullah404/travis-build-config-import-file:before_install.yml@main
  if: env(test-var) is blank
  - source: qasimabdullah404/travis-build-config-import-file:install.yml@main
  if: env(test-var) is present
  
  script: true
