os: linux
language: shell

install: skip

script:
  - sleep 1
jobs:
  include:
    - stage: test-1
      #name: trusty
      arch: arm64-graviton2
      group: edge
      virt: vm
    - stage: test-1
      #name: xenial
      arch: arm64-graviton2
      group: edge
      virt: lxd
