jobs:
  include:
    - os: linux
      arch: ppc64le
      dist: focal
      language: java
      jdk: openjdk8
      
      addons:
        apt:
          packages:
            - xmlstarlet
            - ruby
            - groovy
      
      script:
        - echo $JAVA_HOME
        - mvn -version
