language: node_js
node_js:
  - "8"
before_install:
  - mysql -e 'CREATE DATABASE fonestorm CHARACTER SET utf8 COLLATE utf8_general_ci;'
install: skip
script: true
env:
  - CXX=g++-4.8
addons:
  mariadb: '10.2'
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy
