jobs:
  include:
    - os: linux
      dist: focal
      language: python
      python:
        - 3.10.0
      script: true
    - os: linux
      dist: bionic
      language: python
      python:
        - 3.10.0
      script: true
    - os: linux
      dist: xenial
      language: python
      python:
        - 3.10.0
      script: true
