jobs:
  include:
  - stage: one
    script:
      - echo "--"
  - stage: two
    if: env(tier) = stack
    script:
      - |
        if [ $current == 0 ];then
            echo "---"
        fi
os: linux
dist: xenial
language: shell
