jobs:
  include:
    - os: linux
      dist: precise
      language: php
      php:
        - 5.3
      script: true
      
    - os: linux
      dist: trusty
      language: php
      php:
        - 5.3
      script: true
      
    - os: linux
      dist: precise
      language: php
      php:
        - 5.4
      script: true
      
    - os: linux
      dist: trusty
      language: php
      php:
        - 5.4
      script: true
      
    - os: linux
      dist: precise
      language: php
      php:
        - 5.5
      script: true
      
    - os: linux
      dist: trusty
      language: php
      php:
        - 5.5
      script: true
