jobs:
  include:
    - os: linux
      dist: focal
      arch: ppc64le
      jdk: openjdk17
      script:
        - sleep 1
    - os: linux
      dist: focal
      arch: s390x
      jdk: openjdk13
      script:
        - sleep 2
    - os: linux
      dist: focal
      arch: arm64
      jdk: openjdk11
      script:
        - sleep 3
