version: ~> 1.0
sudo: none
os: linux
language: java
install: skip
stages:
  - name: test
  - name: release
jobs:
  include:
    - script: sleep 1
    - stage: release
      arch: arm64
      script: sleep 2
    - stage: release
      arch: amd64
      script: sleep 3
