jobs:
  include:
    - os: linux
      dist: focal
      language: shell
      vm:
        size: medium
      script:
        - free -m
        - nproc
      
    - os: linux
      dist: focal
      language: shell
      vm:
        size: large
      script:
        - free -m
        - nproc
      
    - os: linux
      dist: focal
      language: shell
      vm:
        size: x-large
      script:
        - free -m
        - nproc
