os: linux
dist: xenial
language: python
python: 3.8
cache:
  yarn: true
  directories:
    - node_modules
  pip: true
  directories:
    - $HOME/.cache/pip
before_install:
  - nvm install 14
  - nvm use 14
  - npm i yarn -g
install:
  - pip install -r requirements.txt
  - yarn install
script: true
