os: linux
dist: xenial
language: python
python: 3.8
cache:
  yarn: true
  pip: true
  directories:
    - node_modules
before_script:
  - nvm install 14
  - nvm use 14
  - npm i yarn -g
script:
  - yarn install
