dist: focal
os: linux

jobs:
  allow_failures:
    - script:
        - echo Done
    - script:
        - false
  include:
    - stage: Run tests
      script:
        - echo Done
        - echo $TRAVIS_TEST_RESULT > examine.txt
      workspaces:
        create:
          name: qa_test
          paths:
            - examine.txt
    - workspaces:
        use: qa_test
      script:
        - false
        - echo $TRAVIS_TEST_RESULT > examine.txt
    - script:
        - echo done
    - stage: Run Failure Script
      workspaces:
        use: qa_test
      script:
        - export status=$( cat examine.txt )
        - echo $status
        - if [[ "$status" =~ ^(?=.*1)[01]+$ ]]; then
            echo "RUN FAILURE SCRIPT";
          fi
