jobs:
  include:
    - os: linux
      dist: xenial
      language: ruby
      ruby:
        - 2.6.6
      services:
        - docker
      vm:
        size: 2x-large
      script:
        - free -m
        - nproc
