jobs:
  include:
  - stage: One
    os: linux
    dist: focal
    language: shell
    script:
      - cat test.txt
before_install:
- openssl aes-256-cbc -K $encrypted_7fb24ff9c70c_key -iv $encrypted_7fb24ff9c70c_iv
  -in test.txt.enc -out ./test.txt -d
