dist: bionic
language: node_js
node_js:
  - 14
git:
  quiet: true
branches:
  only:
  - /.*/
before_install:
  - sleep 2
before_script:
  - sleep 2

jobs:
  include:
    - stage: Performance test
      script:
      - sleep 2
      name: "Performance tests"
      #if: type = api
