language: node_js

node_js:
- "14"

matrix:
fast_finish: true

env:
global:
- AWS_DEFAULT_REGION=eu-north-1

before_script:
- pip3 install pip3 --upgrade --user
- pip3 install awscli --upgrade --user
- export PATH=$PATH:$HOME/.local/bin
- pip3 install --user aws-sam-cli


script: true

notifications:
email:
on_failure: always
