os: linux
dist: xenial
language: php
php: 7.4
before_install:
   - nvm install --lts
   - nvm use --lts
script:
  - php -version
  - node -v
  - npm -v
  - rvm use 2.5.3
  - gem install dpl

#before_deploy:
#  - export CHANGELOG=$(cat CHANGELOG-EXAMPLE.md)
#  - echo $CHANGELOG
#before_deploy:
#   - export CHANGELOG=$(cat CHANGELOG-EXAMPLE.md)
#   - git config --local user.name "qasim-at-tci"
#   - git config --local user.email "qasim.abdullah@travis-ci.org"
#   - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
#   - git tag $TRAVIS_TAG
#deploy:
#  provider: releases
#  token: $GITHUB_TOKEN
#  file: README.md
#  #release_notes: "$CHANGELOG"
#  release_notes: "Release Notes"
#  on:
#    repo: qasim-test-org/travis-test-builds
#    branch: main
#    #tags: true
#  draft: true
#  prerelease: true
#  skip_cleanup: true
