jobs:
  include:
    - os: linux
      dist: bionic
      arch: arm64
      language: shell
      script: true
    - os: linux
      dist: bionic
      arch: arm64
      virt: vm
      language: shell
      script: true
