jobs:
  include:
    - os: linux
      arch: ppc64le
      dist: focal
      language: java
      jdk: openjdk8
      
      addons:
        apt:
          packages:
            - xmlstarlet
            - ruby
            - groovy
      env:
        global:
          - JAVA_HOME=/usr/lib/jvm/adoptopenjdk-8-hotspot-ppc64el
      
      script:
        - echo $JAVA_HOME
        - mvn -version
