dist: bionic
language: ruby
rvm:
  - 2.5.7
before_install:
  #- sudo rm -rf /var/lib/elasticsearch/nodes
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo chown -R elasticsearch:elasticsearch /usr/local/bin/elasticsearch-env
  - sudo service elasticsearch restart
  - gem install bundler -v '1.17.3'
before_script:
- sleep 20
- curl -XGET 'http://localhost:9200'
- "elasticsearch --version"
services:
  - postgresql
  - mysql
  - elasticsearch
  - redis-server
script:
  - sleep 5
addons:
  postgresql: "9.4"
  apt:
    sources:
      - elasticsearch-2.x
    packages:
      elasticsearch
