os: linux
dist: focal
language: shell
services:
  - docker
before_install:
  - sudo systemctl restart docker
  - cat /etc/docker/daemon.json
  - echo '{"max-concurrent-downloads": 1}' | sudo tee /etc/docker/daemon.json
  - echo '{"max-concurrent-uploads": 1}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
  - cat /etc/docker/daemon.json
script: true
