os: linux
dist: focal
install: skip
before_script:
  - mysql --version
  - sudo systemctl start mysql
  - mysql -uroot -e "SHOW VARIABLES LIKE 'innodb_page_size';"
  - sudo systemctl stop mysql
  - sudo echo -e "[mysqld]\nmax_allowed_packet = 1G\ninnodb_log_file_size = 2G\ninnodb_log_buffer_size = 512M" >> /etc/mysql/my.cnf
  - sudo systemctl start mysql
script:
  - mysql -uroot -e "SHOW VARIABLES LIKE 'innodb_page_size';"
