dist: focal
language: ruby
rvm: 2.7.4
services:
- postgresql
before_script:
- sudo systemctl restart postgresql@13-main
- sleep 10
- psql -c 'create database travis_ci_test;' -U postgres
script: true
