language: shell

script:
  - sleep 2
jobs:
  include:
    - os: linux
      dist: focal
      arch: arm64-graviton2
      virt: lxd
      group: edge
    - os: linux
      dist: focal
      arch: amd64
      virt: vm
