os: linux
dist: focal
language: shell

jobs:
  include:
    - if: tag IS present
      script:
        - echo "Tagged build"
        - echo $TRAVIS_TAG
    - before_install:
      - |
        if [[ -n $TRAVIS_TAG ]]; then
          git fetch origin main:main   
          if ! (git branch --contains "$TRAVIS_TAG" | grep -qxE '. main'); then
            travis_terminate 0
          fi
        fi
      script:
        - echo "Branch build"
