os: linux
language: shell
dist: xenial
before_install:
  - sudo rm -fr ~/.pyenv
  - sudo rm -fr /opt/pyenv/
  - curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
  - pyenv update
  - pyenv install 3.7.2
  - pyenv global 2.7.2
jobs:
  include:
    - script:
        - python --version
        #- docker version  # Verify docker downgrade.
        #- docker-compose --version
