language: node_js

node_js:
- "14"

matrix:
fast_finish: true

env:
global:
- AWS_DEFAULT_REGION=eu-north-1

before_script:
- pyenv local 3.9.7
- pip install pip --upgrade --user
- pip install awscli --upgrade --user
- export PATH=$PATH:$HOME/.local/bin
- pip install --user aws-sam-cli


script: true

notifications:
email:
on_failure: always
