jobs:
  include:
    - os: linux
      dist: precise
      language: php
      php:
        - 5.3
      before_install:
        - composer self-update
      script: true
      
    - os: linux
      dist: precise
      language: php
      php:
        - 5.4
      before_install:
        - composer self-update
      script: true
      
    - os: linux
      dist: trusty
      language: php
      php:
        - 5.4
      before_install:
        - composer self-update
      script: true
      
    - os: linux
      dist: precise
      language: php
      php:
        - 5.5
      before_install:
        - composer self-update
      script: true
      
    - os: linux
      dist: trusty
      language: php
      php:
        - 5.5
      before_install:
        - composer self-update
      script: true
