os: linux
arch: s390x
dist: focal
language: node_js
node_js: 14
before_install:
  #- git config --global url."ssh://git@".insteadOf git://
  - npm install -g npm@8.10.0
  #- sudo pip install --upgrade pip

install:
  - npm install

script: true
