os: linux
dist: xenial
language: python
python: 3.8
cache:
  yarn: true
  directories:
    - node_modules
  pip: true
  directories:
    - $HOME/.cache/pip
before_script:
  - nvm install 14
  - nvm use 14
  - npm i yarn -g
  - yarn install
script:
  - echo done
