jobs:
  include:
    - os: linux
      dist: precise
      language: php
      php: 5.6.0
      script: true
      
    - os: linux
      dist: xenial
      language: php
      php: 5.6.0
      script: true
