os:
  - linux
  - osx
dist: bionic
osx_image: xcode12.5
language: node_js
node_js:
  - 14
env:
  - if [$TRAVIS_OS_NAME == "osx"]; then CONFIG=Debug Platform=macos fi
  - if [$TRAVIS_OS_NAME == "osx"]; then CONFIG=Release PLATFORM=macos fi
  - if [$TRAVIS_OS_NAME == "osx"]; then CONFIG=Debug PLATFORM=iOS fi
  - if [$TRAVIS_OS_NAME == "osx"]; then CONFIG=Release PLATFORM=iOS fi
jobs:
  include:
    - os: linux
      dist: focal
      env:
        - test=1
    - os: linux
      dist: focal
      env:
        - test=2
script: true
