dist: bionic
language: node_js
node_js:
  - 14
env:
  - CONFIG=Debug Platform=macos
  - CONFIG=Release PLATFORM=macos
  - CONFIG=Debug PLATFORM=iOS
  - CONFIG=Release PLATFORM=iOS
jobs:
  include:
    - os: linux
      dist: focal
      env:
        - test=1
    - os: linux
      dist: focal
      env:
        - test=2
