os: linux

jobs:
  include:
    - dist: bionic
      language: bash
      install:
        - pyenv install 3.8.1
        - pyenv global 3.8.1
        - nvm install 14
        - nvm use 14
      script:
        - python --version
        - node --version
