jobs:
  include:
    - stage: "TESTS"
      name: "TEST"
      os: linux
      node_js: '12'
      language: node_js
      dist: xenial
      script: true
    - stage: "TESTS"
      name: "TEST"
      os: linux
      node_js: '13'
      language: node_js
      dist: xenial
      script: true
    - stage: "TESTS"
      name: "__TEST"
      os: linux
      node_js: '14'
      language: node_js
      dist: xenial
      script: true
