jobs:
 include:
  - arch: amd64
    os: linux
    dist: xenial
    language: php
    php: 7.2
    script:
     - gcloud version
     - sudo apt-get update && sudo apt-get install google-cloud-sdk=360.0.0
     - gcloud version
