services:
  - postgresql
jobs:
  include:
    - os: linux
      dist: focal
      language: ruby
      before_script:
        - sudo systemctl restart postgresql@13-main
        - sleep 10
      script:
        - psql -c 'create database travis_ci_test_1;' -U postgres
        - psql -c "create role travis login;" -U postgres
        - psql -c 'create database travis_ci_test_2;' -U travis
