os:
  - linux
  - osx
dist: bionic
osx_image: xcode12.5
language: node_js
node_js:
  - 14
env:
  - CONFIG=Debug Platform=macos
  - CONFIG=Release PLATFORM=macos
  - CONFIG=Debug PLATFORM=iOS
  - CONFIG=Release PLATFORM=iOS
  jobs:
    - if [$TRAVIS_OS_NAME == "osx"]; then test=1 fi
    - if [$TRAVIS_OS_NAME == "linux"]; then test=2 PLATFORM=macos fi
script: true
