os: linux
dist: focal
language: shell

script:
  - sleep 1
jobs:
  include:
    - os: linux
      dist: focal
      arch: arm64-graviton2
      virt: vm
      group: edge
    - os: linux
      dist: focal
