jobs:
  include:
    - os: linux
      dist: xenial
      language: python
      python:
        - '3.7'
      services:
        - postgresql
      addons:
        postgresql: '10'
      apt:
        packages:
          - postgresql-10
          - postgresql-client-10
      before_install:
        - sudo lsof -i -P -n
        - travis_retry npm install --global dredd@13.1.2
        - travis_retry curl -s -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.1.1-amd64.deb
        - sudo dpkg -i --force-confnew elasticsearch-7.1.1-amd64.deb
        - sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install mapper-murmur3
        - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
        - sudo service elasticsearch restart
        - sudo lsof -i -P -n
      before_script:
        - until curl --silent -XGET --fail http://localhost:9200; do printf '.'; sleep 1;
          done
      script: true
    - os: linux
      dist: focal
      language: python
      python:
        - '3.7'
      services:
        - postgresql
      addons:
        postgresql: '10'
      apt:
        packages:
          - postgresql-10
          - postgresql-client-10
      before_install:
        - sudo lsof -i -P -n
        - travis_retry npm install --global dredd@13.1.2
        - travis_retry curl -s -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.1.1-amd64.deb
        - sudo dpkg -i --force-confnew elasticsearch-7.1.1-amd64.deb
        - sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install mapper-murmur3
        - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
        - sudo service elasticsearch restart
        - sudo lsof -i -P -n
      before_script:
        - until curl --silent -XGET --fail http://localhost:9200; do printf '.'; sleep 1;
          done
      script: true
