language: java
sudo: required
dist: xenial
before_install:
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install java 16.0.2-open
  - java -version
script:
  - java -version
