jobs:
  iclude:
    - stage: TEST A
      dist: xenial
      language: java
      services: docker
      script:
        - sleep 20
    - stage: TEST B
      dist: xenial
      language: java
      services: docker
      script:
        - sleep 30
    - stage: TEST C
      dist: xenial
      language: java
      services: docker
      script:
        - sleep 50
