jobs:
  include:
  - stage: setup
    script:
    - echo "--"
  if: env(tier) = stack
  - stage: env-stack
    script: if [ $CURRENT_STATUS == 0 ];then echo "----" fi
os: linux
dist: xenial
language: shell
