jobs:
  include:
    - language: minimal

      os: linux
      dist: focal
      arch: ppc64le
      group: edge

      install: skip

      script: true
    - language: minimal

      os: linux
      dist: focal
      arch: s390x

      install: skip

      script: true
