language: node_js
sudo: required
services:
- docker
node_js:
- '14'
arch:
- arm64-graviton2
os: linux
virt: vm
group: edge
addons:
  snaps:
  - yq
script:
- echo $SECRET_ENV_VAR
env:
  global:
  - secure: eYKoqo5naze63G4/d6Xr6Tf7jk1HK9YyEmsX3/USu4/8kHiE7G70T7zrq/38mwOqKJBiaOZmairlODitC0UJQSLxjmuchF10Wud0vgZlDlVdhP00wI6xcmWRptl0Kf8uEOTgHhqnz/sunoSyn2Qm9u/3LE36ilc96Z47RyGxRWk7zLUbdxrxmkhN/4oYIWDJIKIXrIT+eoUsRGOq6Bp6ndUdl9MFt6SZH/NAWFWVEq2Qsb4DqKhBUf+dQCORdWaWXIzfedxLaNYl4xRbHM1tf88ui0m7vHRd/DIIcMtRnOSV6SSB8QaFENrPerYVzq2Pq7BQHgkughI6Nz3GDLluAnvP1R2RQCHulxqySBiAddb31AGtTjaN6D4NnbsIAzenCmIz+Oyr4aLcAEErmVsuHyNW4vH/92Cj/+nl/gluAE9CVJL9PCASwTSpWcwRB9p4uYzziuJpAmcVOqVF5LKEzXxsDKQZgjih5HOQ1H3KDAWn1DM/WD49wKYdnTzUe6N8E/kp/VcavP0l263yBqGLEuErk8QLhhM1+E5wmH+L4aJgTwxcFVo0PLoGyK5TsBX/EKIqy1kbZ7/x23CwuCyIceqZffUIcVKkGSIoBT1iSJZLOovWgSHz5H7e2UfQzY+NBaFC82f0k0++WdfBABSrytZpvzYgEtMYqBWX4UDZoUA=
  - secure: n0JtjoW3tvHBlJRIPIxSoKNRFxi96/TqFWIjAIiQ+wYpCAIl4Z1SqTTr9r9TZ0M0NG+NvIFzcxrzZ3hdC+A3Inazgi4GHUCeLGqrKlxWPacdDPXk9spLVRIoOcYEiniIh7f9pYEvgfyFBbTbdbXedUv2mGmRxEyVOMWYrxnbTre42TAeSj/8kEdm2G67IIbORMFjhu99ml4V6NC4dpwL6Y625w/AM16CO40k63VHLbxs4+iQ3dk/rH0s/UaPmWZG9GlUDevNpSeeA/QdXZxnWxNLqKZawQHuupYcYs2O9VBHTDLyK0pnbRvt9DnrZS11+MbC/JezeljfexXZ7RGiZmW7WU7WUcb3Xlvw3nbJtR796HkJLxSP/xHovAedmIceshklHuZljQYlxms7SsTcOEvoo2EsoFPF4Moi38DXW0q5CZSFyoaPQGxPQYIKdIEGn8x45LHtBJx11yS8NANAwPbR/QJwI0r9WhtQ6quJO6Vx148qkkmEMbTF+0kjqU5tD7/SAXPk2gtNKzSdxDuf5VOuKAQmgIcWkVDwV28xW9eg6MuHdo85858BhfeOC7wLxiAP3qRoufCYvYS5p95ZUiPjuvr4PkZeLqYjuPqqsHuxAV0bX2rscpOqqOSFLG/I7mfw1DACBLKP6YELOIcDKdAUA/HmRXe2aHogXJH1jQc=
