jobs:
  include:
    - os: osx
      osx_image: xcode13.2
      language: objective-c
      before_script:
        - sleep 5
        - python -V
        - pip3 install tox
        - sleep 5
      script: true
