os: linux
language: node_js
sudo: required
node_js:
- 16
install: skip
script:
  - df -h

jobs:
  include:
    - arch: arm64-graviton2
      virt: lxd
      group: edge
    - arch: arm64-graviton2
      virt: vm
      group: edge
