jobs:
  include:
    - os: linux
      dist: xenial
      language: java
      before_install:
      - sudo apt-get -y remove default-jdk
      - sudo apt -y autoremove
      - sudo add-apt-repository -y ppa:openjdk-r/ppa
      - sudo apt -y update
      - sudo apt install -y openjdk-13-jdk
      - sudo apt install -y icedtea-plugin
      - sudo update-java-alternatives -s $(sudo update-java-alternatives -l | grep 13 | cut -d " " -f1) || echo '.'
      - java -version
      script: true
    - os: linux
      dist: xenial
      language: java
      before_install:
      - sudo apt-get -y remove default-jdk
      - sudo apt -y autoremove
      - curl -s "https://get.sdkman.io" | bash
      - source "$HOME/.sdkman/bin/sdkman-init.sh"
      - sdk install java 13.0.2-open
      - java -version
      script: true
