jobs:
  include:
    - os: linux
      arch: s390x
      language: shell
      script: true
    - os: linux
      dist: bionic
      arch: s390x
      language: shell
      script: true
    - os: linux
      dist: focal
      arch: s390x
      language: shell
      script: true
