os: linux
dist: focal
install: skip
vm:
  size: 2x-large
before_script:
  - mysql --version
  - sudo systemctl start mysql
  - mysql -uroot -e "SHOW VARIABLES LIKE 'innodb_page_size';"
  - sudo systemctl stop mysql
  - sudo chmod 777 /var/lib/mysql/
  - sudo chmod 777 /var/log/mysql/error.log
  - mysqld --innodb-page-size=32768
  - sudo systemctl start mysql
script:
  - mysql -uroot -e "SHOW VARIABLES LIKE 'innodb_page_size';"
