os: osx
osx_image: xcode13.3
language: node_js
node_js:
  - 14
cache:
  npm: false
addons:
  artifacts: true
before_install:
  #- git config --global url."ssh://git@".insteadOf git://
  - npm install -g npm@8.10.0
  #- sudo pip install --upgrade pip

install:
  - npm install -g travis-ci-cloudfront-invalidation
  - npm install

script:
  - sleep 1
