jobs:
  iclude:
    - stage:
      name: TEST A
      dist: xenial
      language: java
      services: docker
      script:
        - sleep 20
    - stage:
      name: TEST B
      dist: xenial
      language: java
      services: docker
      script:
        - sleep 30
    - stage:
      name: TEST C
      dist: xenial
      language: java
      services: docker
      script:
        - sleep 50
