os: linux
node_js: '13'
language: node_js
dist: xenial
before_install:
- sudo rm -fr ~/.pyenv
- sudo rm -fr /opt/pyenv/
- curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
- pyenv update
- pyenv install 3.8.0
- pyenv global 3.8.0
- pip install -U pip
- pip install awscli
script:
  - python --version
