os: linux
dist: focal
language: minimal
services:
  - docker
before_script:
  - docker build . -t node-hello
  - docker run -d -p 3000:3000 --name node-hello-world node-hello
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
