os: linux
dist: focal
language: shell
services:
  - postgresql
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
before_script:
  - psql -c 'create database travis_ci_test;' -U travis
script:
  - pg_lsclusters
  - sudo pg_createcluster 11 travis_test
  - sudo pg_ctlcluster 11 travis_test start
  - sudo systemctl daemon-reload
  - pg_lsclusters
