jobs:
  include:
    - os: linux
      dist: xenial
      language: shell
      script:
        - export PYENV_ROOT="$HOME/.pyenv"
        - export PATH="$PYENV_ROOT/bin:$PATH"    # if `pyenv` is not already on PATH
        - eval "$(pyenv init --path)"
        - eval "$(pyenv init -)"
        - pyenv install 3.7.1
        - pyenv global 3.7.1
        - python -V
