jobs:
  include:
    - os: linux
      dist: xenial
      language: java
      before_install:
      - sudo apt-get -y remove default-jdk
      - sudo apt -y autoremove
      - sudo add-apt-repository -y ppa:openjdk-r/ppa
      - sudo apt -y update
      - sudo apt install -y openjdk-13-jdk
      - sudo update-java-alternatives -s $(sudo update-java-alternatives -l | grep 13 | cut -d " " -f1) || echo '.'
      - java -version
      script: true
