dist: focal
arch: amd64
language: shell

before_install:
  - |
    if [ $TRAVIS_PULL_REQUEST != "false" ]; then
      isDraft=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST | grep -c "draft")
      if [ $isDraft == 1 ]; then
        echo "Skipping rest of the build phases as its a Draft PR"
        exit 0
      fi
    fi
  - sleep 3
script:
  - echo done
