language: node_js
node_js:
  - 14
  - 16
  - 17
stages:
  - lts
  - previous-lts
  - current
jobs:
  allow_failures:
    - node_js: 17
  include:
    - &testStage
      stage: lts
      node_js: 16
      script:
        - sleep 1
    - stage: lts
      node_js: 16
      script:
        - sleep 2
    - &buildStage
      stage: lts
      node_js: 16
      before_script: skip
      install: skip
      script:
        - sleep 3
    - <<: *testStage
      stage: previous-lts
      node_js: 14
      #if: branch = fc-400-temp-ensure-skeleton-build-ci-passes
    - <<: *buildStage
      stage: previous-lts
      node_js: 14
      #if: branch = fc-400-temp-ensure-skeleton-build-ci-passes
    - <<: *testStage
      stage: current
      node_js: 17
      #if: branch = fc-400-temp-ensure-skeleton-build-ci-passes
    - <<: *buildStage
      stage: current
      node_js: 17
      #if: branch = fc-400-temp-ensure-skeleton-build-ci-passes
