os: linux
language: shell
dist: xenial
before_script:
  - pyenv global 3.7.1
jobs:
  include:
    - script:
        - python --version
        #- docker version  # Verify docker downgrade.
        #- docker-compose --version
