jobs:
  include:
  # Focal
    - os: linux
      arch: ppc64le
      dist: focal
      language: java
      jdk: openjdk8
      
      addons:
        apt:
          packages:
            - xmlstarlet
            - ruby
            - groovy
            
      before_install:
        - sudo apt-get install ant-optional
      before_script:
        - export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-8-hotspot-ppc64el
        - export PATH=$JAVA_HOME/bin:$PATH

      script:
        - groovy --version
        - ant -version
