env: 
  global: 
    - test_var=test
import: 
  - 
    if: env(test_var) = test
    source: "qasimabdullah404/travis-build-config-import-file:before_install.yml@main"
  - 
    if: env(test_var) != test
    source: "qasimabdullah404/travis-build-config-import-file:install.yml@main"
