jobs:
  include:
    - os: linux
      dist: xenial
      language: shell
      before_script:
        - eval "$(pyenv init --path)"
        - pyenv install 3.7.1
        - pyenv global 3.7.1
      script:
        - python -V
        
    - os: linux
      dist: xenial
      language: shell
      before_script:
        - eval "$(pyenv init --path)"
        - pyenv install 3.7.2
        - pyenv global 3.7.1
      script:
        - python -V
