language: shell
jobs:
  include:
    - os: linux
      dist: focal
      jdk: openjdk17
      script: true
    - os: linux
      dist: focal
      jdk: openjdk13
      script: true
    - os: linux
      dist: focal
      jdk: openjdk11
      script: true
