os: linux
dist: focal
language: node_js
install: skip
script: true
before_deploy:
  - ruby -v
  - rvm install 2.7.1
  - rvm use 2.7.1
  - ruby -v
deploy:
  provider: script
  script:
    - gem list dpl
  on:
    all_branches: true
