jobs:
 include:
  - arch: amd64
    os: linux
    dist: focal
    language: ruby
    ruby: 3.0
    script:
     - ruby -v
  - os: osx
    osx_image: xcode13.1
    language: ruby
    ruby: 3.0.3
    script:
     - ruby -v
