os: linux
dist: focal
rvm: 2.6.7

addons:
  apt:
    packages:
      - ca-certificates

services:
  - redis
  - mongodb
before_install:
  - mongo --version
  - sudo apt remove -y mongodb && sudo apt purge -y mongodb && sudo apt autoremove
  - sudo apt-get install -y mongodb-org
script:
  - mongo --version
