jobs:
  include:
    - stage: Tests
      script: true
    - &stuff
      stage: Deploy
      if: env(tier)=stack
      script:
        - echo "---"
    - <<: *stuff
      if: env(current)=0
      script:
        - echo "----"
os: linux
dist: xenial
env:
  - tier=stack current=0
language: shell
