jobs:
  include:
    - language: minimal

      os: linux
      dist: trusty
      language: node_js
      node_js: node
      install: skip

      script: true
    - language: minimal

      os: linux
      dist: xenial
      language: node_js
      node_js: node

      install: skip

      script: true
