language: java
env:
  global:
    - GRADLE_HOME="$PWD/gradle-7.4"
    - PATH=$GRADLE_HOME/bin:$PATH
install: skip
before_script:
  - wget https://services.gradle.org/distributions/gradle-7.4.2-bin.zip
  - unzip -qq gradle-7.4.2-bin.zip
script:
  - ./gradlew run

jobs:
  include:
    - jdk: openjdk7
      dist: trusty
    - jdk: openjdk8
      dist: trusty
    - jdk: openjdk9
      dist: trusty
    - jdk: openjdk10
      dist: trusty
    - jdk: openjdk11
      dist: trusty
    - jdk: openjdk12
      dist: trusty
    - jdk: openjdk13
      dist: trusty
    - jdk: openjdk14
      dist: trusty
    - jdk: openjdk15
      dist: trusty
    - jdk: openjdk16
      dist: trusty
    - jdk: openjdk17
      dist: trusty
      
    - jdk: openjdk7
      dist: xenial
    - jdk: openjdk8
      dist: xenial
    - jdk: openjdk9
      dist: xenial
    - jdk: openjdk10
      dist: xenial
    - jdk: openjdk11
      dist: xenial
    - jdk: openjdk12
      dist: xenial
    - jdk: openjdk13
      dist: xenial
    - jdk: openjdk14
      dist: xenial
    - jdk: openjdk15
      dist: xenial
    - jdk: openjdk16
      dist: xenial
    - jdk: openjdk17
      dist: xenial
      
    - jdk: openjdk7
      dist: bionic  
    - jdk: openjdk8
      dist: bionic
    - jdk: openjdk9
      dist: bionic
    - jdk: openjdk10
      dist: bionic
    - jdk: openjdk11
      dist: bionic
    - jdk: openjdk12
      dist: bionic
    - jdk: openjdk13
      dist: bionic
    - jdk: openjdk14
      dist: bionic
    - jdk: openjdk15
      dist: bionic
    - jdk: openjdk16
      dist: bionic
    - jdk: openjdk17
      dist: bionic
      
    - jdk: openjdk7
      dist: focal  
    - jdk: openjdk8
      dist: focal
    - jdk: openjdk9
      dist: focal
    - jdk: openjdk10
      dist: focal
    - jdk: openjdk11
      dist: focal
    - jdk: openjdk12
      dist: focal
    - jdk: openjdk13
      dist: focal
    - jdk: openjdk14
      dist: focal
    - jdk: openjdk15
      dist: focal
    - jdk: openjdk16
      dist: focal
    - jdk: openjdk17
      dist: focal
      
    - jdk: openjdk7
      dist: jammy
      group: edge
    - jdk: openjdk8
      dist: jammy
      group: edge
    - jdk: openjdk9
      dist: jammy
      group: edge
    - jdk: openjdk10
      dist: jammy
      group: edge
    - jdk: openjdk11
      dist: jammy
      group: edge
    - jdk: openjdk12
      dist: jammy
      group: edge
    - jdk: openjdk13
      dist: jammy
      group: edge
    - jdk: openjdk14
      dist: jammy
      group: edge
    - jdk: openjdk15
      dist: jammy
      group: edge
    - jdk: openjdk16
      dist: jammy
      group: edge
    - jdk: openjdk17
      dist: jammy
      group: edge
