os: linux
dist: bionic
language: ruby
addons:
  apt:
    packages:
      - postgresql-14
      - postgresql-client-14
services:
  - postgresql
env:
  global:
    - PGPORT=5433
    - PGUSER=travis
script:
  - psql --version
