dist: focal
os: linux
language: minimal
before_install:
  # Install sshpass to pass linode creds
  - sudo apt-get install -y sshpass
before_script:
  # Download the file from remote server to build VM
  - sshpass -e scp -o "StrictHostKeyChecking=no" root@172.105.39.242:/home/temp/results.txt $TRAVIS_BUILD_DIR
  # Delete the file from remote server
  - sshpass -e ssh root@172.105.39.242 rm -f /home/temp/results.txt

jobs:
  allow_failures:
    env:
      - ALLOW_FAIL=true
  include:
    - stage: Get file ready to catch subsequent stage jobs results
      before_script: skip
      script:
        - touch results.txt
        - sshpass -e scp -o "StrictHostKeyChecking=no" $TRAVIS_BUILD_DIR/results.txt root@172.105.39.242:/home/temp
    - stage: Run tests
      env:
        - ALLOW_FAIL=true
      script:
        - echo Done
        - echo $TRAVIS_TEST_RESULT > results.txt
        - cat results.txt
        - sshpass -e scp -o "StrictHostKeyChecking=no" $TRAVIS_BUILD_DIR/results.txt root@172.105.39.242:/home/temp
    - env:
        - ALLOW_FAIL=true
      script:
        - false
        - echo $TRAVIS_TEST_RESULT >> results.txt
        - cat results.txt
        - sshpass -e scp $TRAVIS_BUILD_DIR/results.txt root@172.105.39.242:/home/temp
    - script:
        - echo done
    - stage: Run Failure Script
      script:
        - cat results.txt
        - status=$( cat results.txt )
        - echo $status
        - if [[ "$status" =~ [1] ]]; then
            echo "RUN FAILURE SCRIPT";
          fi
