os: linux
dist: xenial
language: node_js
node_js: 16

script: true

deploy:
  - provider: lambda
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_DEFAULT_REGION
    function_name: $ENV
    runtime: nodejs16.x
    timeout: 10
    zip: .
    environment:
      ENV=$ENV
      SENTRY_DSN=$SENTRY_DSN
      STUDIO_AUTHORIZATION_KEY=$STUDIO_AUTHORIZATION_KEY
    edge: true
    on:
      all_branches: true
