jobs:
  include:
    - os: linux
      dist: trusty
      language: php
      php:
        - 8.1snapshot
      script: true
      
    - os: linux
      dist: focal
      language: php
      php:
        - 8.1snapshot
      script: true
