os: linux
dist: bionic
language: python
python:
  - '3.7'
install:
  - if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
      export PATH=${PATH}:/Users/travis/Library/Python/2.7/bin
    fi
  - pip install tox
  - sleep 1
jobs:
  include:
    - os: osx
      osx_image: xcode13.2
      language: objective-c
      script: true
