os: linux
dist: focal
language: ruby
ruby: 2.7.5
before_script:
  - curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.4.deb -o elasticsearch.deb
  - sudo dpkg -i --force-confnew elasticsearch.deb
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo rm -rf /var/lib/elasticsearch/nodes
  - sudo service elasticsearch restart
  - until curl --silent -XGET --fail http://localhost:9200; do printf '...\n'; sleep 2;
    done
script: true
