os: linux
language: go

addons:
  apt:
    packages:
    - gcc
  update: true
env:
  global:
    - GIMME_DEBUG=1

install: skip

script:
  - go version
jobs:
  include:
    - dist: trusty
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy
