jobs:
  include:
  - stage: One
    os: linux
    dist: focal
    language: shell
    script:
      - echo TravisCIKey
before_install:
- openssl aes-256-cbc -K $encrypted_f26e077a6941_key -iv $encrypted_f26e077a6941_iv
  -in test_key.enc -out /test_key -d
- ssh-add ./test_key
- eval "$(ssh-agent -s)"
- chmod 600 ./test_key
